In [3]:
import pandas as pd

In [4]:
import json

In [5]:
data = pd.read_csv("./updated_filtered-columns-data.csv")
print(data)

       Unnamed: 0 committee_id                             committee_name  \
0               0    C00633982                  HARLEY ROUDA FOR CONGRESS
1               1    C00633982                  HARLEY ROUDA FOR CONGRESS
2               2    C00633982                  HARLEY ROUDA FOR CONGRESS
3               3    C00633982                  HARLEY ROUDA FOR CONGRESS
4               4    C00633982                  HARLEY ROUDA FOR CONGRESS
...           ...          ...                                        ...
28641       28641    C00165688  NORTH CAROLINA DEMOCRATIC PARTY - FEDERAL
28642       28642    C00655613                     SUSIE LEE FOR CONGRESS
28643       28643    C00165688  NORTH CAROLINA DEMOCRATIC PARTY - FEDERAL
28644       28644    C00165688  NORTH CAROLINA DEMOCRATIC PARTY - FEDERAL
28645       28645    C00165688  NORTH CAROLINA DEMOCRATIC PARTY - FEDERAL

       report_year     contributor_name contributor_first_name  \
0             2018       BALDWIN, PETER                  PETER
1             2018       BALDWIN, PETER                  PETER
2             2018        DUBOIS, ELLEN                  ELLEN
3             2018         BOWIE, JAMES                  JAMES
4             2018      MIRANDA, JEANNE                 JEANNE
...            ...                  ...                    ...
28641         2020          PERIS, TARA                   TARA
28642         2020        KAPLAN, DAVID                  DAVID
28643         2020  TELLES, CYNTHIA ANN                CYNTHIA
28644         2020  TELLES, CYNTHIA ANN                CYNTHIA
28645         2020  TELLES, CYNTHIA ANN                CYNTHIA

      contributor_last_name contributor_occupation contributor_id  \
0                   BALDWIN              PROFESSOR      C00401224
1                   BALDWIN              PROFESSOR      C00401224
2                    DUBOIS              PROFESSOR            NaN
3                     BOWIE              PROFESSOR      C00401224
4                   MIRANDA              PROFESSOR      C00401224
...                     ...                    ...            ...
28641                 PERIS              PROFESSOR            NaN
28642                KAPLAN              PROFESSOR            NaN
28643                TELLES              PROFESSOR            NaN
28644                TELLES              PROFESSOR            NaN
28645                TELLES              PROFESSOR            NaN

      contribution_receipt_date  contribution_receipt_amount  \
0           2018-08-21 00:00:00                      1000.00
1           2018-07-23 00:00:00                      1000.00
2           2018-09-14 00:00:00                       300.00
3           2018-08-29 00:00:00                       250.00
4           2018-09-05 00:00:00                       250.00
...                         ...                          ...
28641       2020-09-14 00:00:00                         9.00
28642       2020-07-10 00:00:00                       266.67
28643       2020-09-01 00:00:00                         0.33
28644       2020-09-08 00:00:00                         3.33
28645       2020-09-14 00:00:00                         1.67

       contributor_aggregate_ytd election_type election_type_full
0                        5000.00         G2018                NaN
1                        4000.00         G2018                NaN
2                         354.00         G2018                NaN
3                         250.00         G2018                NaN
4                         250.00         G2018                NaN
...                          ...           ...                ...
28641                       9.00           NaN                NaN
28642                     266.67         G2020                NaN
28643                    1767.00             P                NaN
28644                    1770.33             P                NaN
28645                    1772.00             P                NaN

[28646 rows x 14 columns]

In [6]:
data.groupby(['committee_name','contribution_receipt_amount'])['contributor_aggregate_ytd'].agg('sum')

committee_name            contribution_receipt_amount
314 ACTION FUND           100.00                         1000.00
                          250.00                          250.00
ACTBLUE                   0.27                              0.27
                          0.30                           2304.04
                          0.31                            326.64
                                                          ...
XOCHITL FOR NEW MEXICO    500.00                         1000.00
                          1000.00                        1000.00
                          2700.00                        2700.00
YOUNG FOR IOWA, INC.      100.00                          300.00
YUKONG ZHAO FOR CONGRESS  500.00                          500.00
Name: contributor_aggregate_ytd, Length: 1679, dtype: float64

In [7]:
data.groupby(['committee_name','contribution_receipt_amount']).count()

                                                      Unnamed: 0  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                3
                         250.00                                1
ACTBLUE                  0.27                                  1
                         0.30                                 43
                         0.31                                 29
...                                                          ...
XOCHITL FOR NEW MEXICO   500.00                                2
                         1000.00                               1
                         2700.00                               1
YOUNG FOR IOWA, INC.     100.00                                1
YUKONG ZHAO FOR CONGRESS 500.00                                1

                                                      committee_id  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                  3
                         250.00                                  1
ACTBLUE                  0.27                                    1
                         0.30                                   43
                         0.31                                   29
...                                                            ...
XOCHITL FOR NEW MEXICO   500.00                                  2
                         1000.00                                 1
                         2700.00                                 1
YOUNG FOR IOWA, INC.     100.00                                  1
YUKONG ZHAO FOR CONGRESS 500.00                                  1

                                                      report_year  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                 3
                         250.00                                 1
ACTBLUE                  0.27                                   1
                         0.30                                  43
                         0.31                                  29
...                                                           ...
XOCHITL FOR NEW MEXICO   500.00                                 2
                         1000.00                                1
                         2700.00                                1
YOUNG FOR IOWA, INC.     100.00                                 1
YUKONG ZHAO FOR CONGRESS 500.00                                 1

                                                      contributor_name  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                      3
                         250.00                                      1
ACTBLUE                  0.27                                        1
                         0.30                                       43
                         0.31                                       29
...                                                                ...
XOCHITL FOR NEW MEXICO   500.00                                      2
                         1000.00                                     1
                         2700.00                                     1
YOUNG FOR IOWA, INC.     100.00                                      1
YUKONG ZHAO FOR CONGRESS 500.00                                      1

                                                      contributor_first_name  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                            3
                         250.00                                            1
ACTBLUE                  0.27                                              1
                         0.30                                             43
                         0.31                                             29
...                                                                      ...
XOCHITL FOR NEW MEXICO   500.00                                            2
                         1000.00                                           1
                         2700.00                                           1
YOUNG FOR IOWA, INC.     100.00                                            1
YUKONG ZHAO FOR CONGRESS 500.00                                            1

                                                      contributor_last_name  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                           3
                         250.00                                           1
ACTBLUE                  0.27                                             1
                         0.30                                            43
                         0.31                                            29
...                                                                     ...
XOCHITL FOR NEW MEXICO   500.00                                           2
                         1000.00                                          1
                         2700.00                                          1
YOUNG FOR IOWA, INC.     100.00                                           1
YUKONG ZHAO FOR CONGRESS 500.00                                           1

                                                      contributor_occupation  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                            3
                         250.00                                            1
ACTBLUE                  0.27                                              1
                         0.30                                             43
                         0.31                                             29
...                                                                      ...
XOCHITL FOR NEW MEXICO   500.00                                            2
                         1000.00                                           1
                         2700.00                                           1
YOUNG FOR IOWA, INC.     100.00                                            1
YUKONG ZHAO FOR CONGRESS 500.00                                            1

                                                      contributor_id  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                    3
                         250.00                                    1
ACTBLUE                  0.27                                      0
                         0.30                                      0
                         0.31                                      0
...                                                              ...
XOCHITL FOR NEW MEXICO   500.00                                    2
                         1000.00                                   1
                         2700.00                                   1
YOUNG FOR IOWA, INC.     100.00                                    1
YUKONG ZHAO FOR CONGRESS 500.00                                    0

                                                      contribution_receipt_date  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                               3
                         250.00                                               1
ACTBLUE                  0.27                                                 1
                         0.30                                                43
                         0.31                                                29
...                                                                         ...
XOCHITL FOR NEW MEXICO   500.00                                               2
                         1000.00                                              1
                         2700.00                                              1
YOUNG FOR IOWA, INC.     100.00                                               1
YUKONG ZHAO FOR CONGRESS 500.00                                               1

                                                      contributor_aggregate_ytd  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                               3
                         250.00                                               1
ACTBLUE                  0.27                                                 1
                         0.30                                                43
                         0.31                                                29
...                                                                         ...
XOCHITL FOR NEW MEXICO   500.00                                               2
                         1000.00                                              1
                         2700.00                                              1
YOUNG FOR IOWA, INC.     100.00                                               1
YUKONG ZHAO FOR CONGRESS 500.00                                               1

                                                      election_type  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                   3
                         250.00                                   1
ACTBLUE                  0.27                                     0
                         0.30                                     0
                         0.31                                     0
...                                                             ...
XOCHITL FOR NEW MEXICO   500.00                                   2
                         1000.00                                  1
                         2700.00                                  1
YOUNG FOR IOWA, INC.     100.00                                   1
YUKONG ZHAO FOR CONGRESS 500.00                                   1

                                                      election_type_full
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                        0
                         250.00                                        0
ACTBLUE                  0.27                                          0
                         0.30                                          0
                         0.31                                          0
...                                                                  ...
XOCHITL FOR NEW MEXICO   500.00                                        0
                         1000.00                                       0
                         2700.00                                       0
YOUNG FOR IOWA, INC.     100.00                                        0
YUKONG ZHAO FOR CONGRESS 500.00                                        0

[1679 rows x 12 columns]

In [8]:
data.groupby(
    ['committee_name','contribution_receipt_amount']
).agg(
    {
        # Find sum of the duration column
        'contributor_aggregate_ytd': [sum]
    }
)

                                                     contributor_aggregate_ytd
                                                                           sum
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                        1000.00
                         250.00                                         250.00
ACTBLUE                  0.27                                             0.27
                         0.30                                          2304.04
                         0.31                                           326.64
...                                                                        ...
XOCHITL FOR NEW MEXICO   500.00                                        1000.00
                         1000.00                                       1000.00
                         2700.00                                       2700.00
YOUNG FOR IOWA, INC.     100.00                                         300.00
YUKONG ZHAO FOR CONGRESS 500.00                                         500.00

[1679 rows x 1 columns]

In [9]:
data.groupby(
    ['committee_name','contribution_receipt_amount']
).agg(
    {
        # Find sum of the duration column
        'contribution_receipt_amount': [sum]
    }
)

                                                     contribution_receipt_amount
                                                                             sum
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                           300.00
                         250.00                                           250.00
ACTBLUE                  0.27                                               0.27
                         0.30                                              12.90
                         0.31                                               8.99
...                                                                          ...
XOCHITL FOR NEW MEXICO   500.00                                          1000.00
                         1000.00                                         1000.00
                         2700.00                                         2700.00
YOUNG FOR IOWA, INC.     100.00                                           100.00
YUKONG ZHAO FOR CONGRESS 500.00                                           500.00

[1679 rows x 1 columns]

In [10]:
data.groupby(['committee_name','contribution_receipt_amount']).sum().groupby('committee_name').cumsum()

                                                      Unnamed: 0  report_year  \
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                            48229         6058
                         250.00                            54898         8076
ACTBLUE                  0.27                              20488         2020
                         0.30                             464333        88817
                         0.31                             865828       147367
...                                                          ...          ...
XOCHITL FOR NEW MEXICO   500.00                            25166         6055
                         1000.00                           32021         8073
                         2700.00                           38875        10091
YOUNG FOR IOWA, INC.     100.00                            27024         2020
YUKONG ZHAO FOR CONGRESS 500.00                            20139         2020

                                                      contributor_aggregate_ytd
committee_name           contribution_receipt_amount
314 ACTION FUND          100.00                                         1000.00
                         250.00                                         1250.00
ACTBLUE                  0.27                                              0.27
                         0.30                                           2304.31
                         0.31                                           2630.95
...                                                                         ...
XOCHITL FOR NEW MEXICO   500.00                                         1250.00
                         1000.00                                        2250.00
                         2700.00                                        4950.00
YOUNG FOR IOWA, INC.     100.00                                          300.00
YUKONG ZHAO FOR CONGRESS 500.00                                          500.00

[1679 rows x 3 columns]

In [11]:
data.contribution_receipt_amount.value_counts()

0.01      4686
25.00     3190
50.00     2725
100.00    2209
10.00     2016
          ...
90.91        1
886.66       1
188.00       1
81.00        1
15.80        1
Name: contribution_receipt_amount, Length: 453, dtype: int64

In [12]:
data.sort_values("contribution_receipt_amount", ascending = False).head()

,Unnamed: 0,committee_id,committee_name,report_year,contributor_name,contributor_first_name,contributor_last_name,contributor_occupation,contributor_id,contribution_receipt_date,contribution_receipt_amount,contributor_aggregate_ytd,election_type,election_type_full
26178,26178,C00744946,BIDEN VICTORY FUND,2020,"TELLES, CYNTHIA",CYNTHIA,TELLES,PROFESSOR,NaN,2020-05-03 00:00:00,41100.0,41100.0,P,NaN
26181,26181,C00744946,BIDEN VICTORY FUND,2020,"TELLES, CYNTHIA",CYNTHIA,TELLES,PROFESSOR,NaN,2020-06-12 00:00:00,40000.0,81100.0,P,NaN
25358,25358,C00010603,DNC SERVICES CORP / DEMOCRATIC NATIONAL COMMITTEE,2020,"TELLES, CYNTHIA",CYNTHIA,TELLES,PROFESSOR,NaN,2020-05-03 00:00:00,35500.0,35500.0,G2020,NaN
27766,27766,C00010603,DNC SERVICES CORP / DEMOCRATIC NATIONAL COMMITTEE,2020,"OPIE, CATHERINE S",CATHERINE,OPIE,PROFESSOR,NaN,2020-10-01 00:00:00,27225.0,27379.0,G2020,NaN
27585,27585,C00010603,DNC SERVICES CORP / DEMOCRATIC NATIONAL COMMITTEE,2020,"WALSKE, JENNIFER MAYE",JENNIFER,WALSKE,PROFESSOR,NaN,2020-08-06 00:00:00,25000.0,27800.0,G2020,NaN

In [13]:
newlist = data['committee_name'].drop_duplicates().to_list()

In [14]:
print(newlist)

['HARLEY ROUDA FOR CONGRESS', 'ACTBLUE', 'FRIENDS OF DANA BALTER', 'IT STARTS TODAY', 'END CITIZENS UNITED', 'LATINO VICTORY FUND', 'ROSEN FOR NEVADA', 'KATIE PORTER FOR CONGRESS', 'CALIFORNIA DEMOCRATIC PARTY', 'SHARICE FOR CONGRESS', 'SCHOLTEN4IOWA CAMPAIGN COMMITTEE', 'DSCC', 'DCCC', 'BRYAN CAFORIO FOR CONGRESS', 'COURAGE CAMPAIGN SUPER PAC', 'AMMAR CAMPA FOR CONGRESS', "EMILY'S LIST", 'EQUALITY PAC', 'BARRAGAN FOR CONGRESS', 'ANDREW JANZ FOR CONGRESS', 'MCCASKILL FOR MISSOURI', 'CODE BLUE', 'FRIENDS OF BERNIE SANDERS', 'BETO FOR TEXAS', 'NATIONAL DEMOCRATIC REDISTRICTING PAC', 'SWING LEFT', "DNC SERVICES CORP./DEM. NAT'L COMMITTEE", 'COMMITTEE TO ELECT VICTOR SWANSON', 'SEA CHANGE LEADERSHIP PAC', 'KATIE HILL FOR CONGRESS', 'DEMOCRACY FOR AMERICA', 'RADINOVICH FOR CONGRESS', 'PROGRESSIVE TURNOUT PROJECT', 'SOUTHERN CALIFORNIA FUND', 'CALIFORNIA REPUBLICAN PARTY FEDERAL ACCT.', 'NEW JERSEY DEMOCRATIC STATE COMMITTEE', 'FRIENDS OF SHERROD BROWN', 'DONNELLY FOR INDIANA', 'LOS ANGELES COUNTY DEMOCRATIC CENTRAL COMMITTEE', 'MCNERNEY FOR CONGRESS', 'SHERMAN FOR CONGRESS', 'COLLINS FOR SENATOR', 'NORTH CAROLINA DEMOCRATIC PARTY - FEDERAL', 'CITIZENS FOR WATERS', 'ELIZABETH FOR MA, INC', 'MOVEON.ORG POLITICAL ACTION', 'PAC FOR A CHANGE', 'DAVE MIN FOR CONGRESS', 'SCHIFF FOR CONGRESS', 'BILL NELSON FOR US SENATE', 'BERA FOR CONGRESS', 'NRSC', 'MIKE ESPY FOR SENATE CAMPAIGN COMMITTEE', 'MCCASKILL 2018 VICTORY', 'JOHN LEWIS FOR CONGRESS', 'NEVADA STATE DEMOCRATIC PARTY', 'IOWA DEMOCRATIC PARTY', 'NANCY PELOSI FOR CONGRESS', 'CHC BOLD PAC', 'COMMITTEE TO ELECT RICHARD OJEDA', 'ALEXANDRIA OCASIO-CORTEZ FOR CONGRESS', 'ELIZABETH PANNILL FLETCHER FOR CONGRESS', 'MIKIE SHERRILL FOR CONGRESS', 'TOM MALINOWSKI FOR CONGRESS', 'ONWARD TOGETHER COMMITTEE', 'FINKENAUER VICTORY FUND', 'DOUG JONES FOR SENATE COMMITTEE', 'JUANA MATIAS FOR CONGRESS', 'GREAT AMERICA COMMITTEE', 'CONOR LAMB FOR CONGRESS', 'ELIZABETH HENG FOR CONGRESS', 'BIGGINS FOR VIRGINIA', 'IAN TODD FOR CONGRESS', 'LINDA COLEMAN FOR CONGRESS', 'AMY MCGRATH FOR CONGRESS', 'SUSAN WILD FOR CONGRESS', 'CINDY AXNE FOR CONGRESS', 'KEVIN DE LEON FOR SENATE', 'KEN HARBAUGH FOR CONGRESS', 'BREDESEN VICTORY FUND', 'WILLIAMS FOR MONTANA', 'DONNA SHALALA FOR CONGRESS', 'ANDY KIM FOR CONGRESS', 'RANDY BRYCE FOR CONGRESS', 'ROUDA HILL VICTORY FUND', 'BRINDISI FOR CONGRESS', 'CASTEN FOR CONGRESS', 'KENDRA HORN FOR CONGRESS', 'SCHIFF LEADS PAC', 'ELECT CAROLYN LONG', 'ALISON HARTSON 2018', 'DINICOLA FOR CONGRESS', 'TJ COX FOR CONGRESS', 'FRIENDS OF DAN FEEHAN', 'WESTSIDE DEMOCRATIC HQ FEDERAL', 'PLANNED PARENTHOOD ADVOCACY PROJECT LOS ANGELES COUNTY ACTION FUND', 'CAROLYN FOR CONGRESS', 'MJ FOR TEXAS', 'DELGADO FOR CONGRESS', '314 ACTION FUND', 'SODERBERG FOR CONGRESS', 'SPANBERGER FOR CONGRESS', 'HIRAL FOR CONGRESS', 'ELISSA SLOTKIN FOR CONGRESS', 'LESLIE COCKBURN FOR CONGRESS', 'CHUY GARCIA FOR CONGRESS', 'MIKE LEVIN FOR CONGRESS', 'JOE CUNNINGHAM FOR CONGRESS', 'CISNEROS FOR CONGRESS', 'SAAD FOR CONGRESS', 'BIG SKY VALUES PAC', 'BRIAN FORDE FOR CONGRESS', 'OSMACK FOR MISSOURI', 'KIRKPATRICK FOR CONGRESS', 'KULKARNI FOR CONGRESS', 'KATHY MANNING FOR CONGRESS', 'RED TO BLUE CA', 'BREDESEN FOR SENATE', 'DEBBIE FOR CONGRESS', 'DR KIM SCHRIER FOR CONGRESS', 'ELAINE FOR CONGRESS', 'FRIENDS OF STEVE BACHER', 'FINKENAUER FOR CONGRESS', 'LAUREN UNDERWOOD FOR CONGRESS', 'FRIENDS OF RANDY WADKINS', 'WEXTON FOR CONGRESS', 'COLIN ALLRED FOR CONGRESS', 'FRIENDS OF JONATHAN EBEL', 'FUTURE NOW FUND', 'XOCHITL FOR NEW MEXICO', 'HALEY STEVENS FOR CONGRESS', 'FRIENDS OF DANNER KLINE', 'JAY FOR TEXAS', 'JOSH HARDER FOR CONGRESS', 'BATESON FOR CONGRESS', "O'CONNOR FOR CONGRESS", 'KIER FOR CONGRESS', 'TEXAS VICTORY 2018', 'SCOTT PETERS FOR CONGRESS', 'HEIDI FOR SENATE', 'ROSEN VICTORY FUND', 'JEFF MERKLEY FOR OREGON', 'JULIA BROWNLEY FOR CONGRESS', 'KAMALA HARRIS FOR SENATE', 'CONGRESSIONAL PROGRESSIVE CAUCUS PAC', 'JSTREETPAC', 'BEND THE ARC JEWISH ACTION INC. PAC', 'JIMMY GOMEZ FOR CONGRESS', 'FEINSTEIN FOR SENATE 2024', 'GIFFORDS PAC', 'PROGRESSIVE VOTE AKA PROGRESSIVE DEMOCRATS OF AMERICA', 'KAREN BASS FOR CONGRESS', 'SMP', 'WORKING FAMILIES PARTY NATIONAL POLITICAL ACTION COMMITTEE', 'MONTANANS FOR TESTER', 'GILLIBRAND FOR SENATE', 'MANCHIN FOR WEST VIRGINIA', 'AMERICAN GASTROENTEROLOGICAL ASSOCIATION INC. PAC', 'HOUSE MAJORITY PAC', 'TED CRUZ FOR SENATE', 'COLOROFCHANGE PAC', 'SCHNEIDER FOR CONGRESS', 'CREATIVE MAJORITY POLITICAL ACTION COMMITTEE', 'BOB CASEY FOR SENATE INC', 'KLOBUCHAR FOR MINNESOTA ', 'TONY CARDENAS FOR CONGRESS', 'FRIENDS OF CHERI BUSTOS', 'AMERICAN COLLEGE OF RHEUMATOLOGY (RHEUMPAC)', 'BILL FOSTER FOR CONGRESS', 'BATTLEGROUND VICTORY FUND 2018', 'ILHAN FOR CONGRESS', 'SCHAKOWSKY FOR CONGRESS', 'WARREN FOR PRESIDENT, INC.', 'DEMOCRACY ENGINE, INC., PAC', 'PETERS FOR MICHIGAN', 'SWALWELL FOR AMERICA', 'AMERICAN POSSIBILITIES PAC', 'AMY FOR AMERICA', 'FRIENDS OF LUCY MCBATH', 'MARK KELLY FOR SENATE', 'MAX ROSE FOR CONGRESS', 'NATIONAL DEMOCRATIC TRAINING COMMITTEE PAC', 'BERNIE 2020', 'THE LINCOLN PROJECT', 'CITIZENS FOR BOYLE', 'DNC SERVICES CORP / DEMOCRATIC NATIONAL COMMITTEE', 'SIERRA CLUB POLITICAL COMMITTEE', 'KEVIN MCCARTHY FOR CONGRESS', 'KLOBUCHAR FOR MINNESOTA', 'DONALD J. TRUMP FOR PRESIDENT, INC.', 'NUESTRO PAC', 'MARK KELLY VICTORY FUND', 'LMG PAC', 'NRCC', 'BOLD DEMOCRATIC 2020', 'SWALWELL FOR CONGRESS', 'WIN THE ERA PAC', 'DR. AL GROSS FOR U.S. SENATE', 'NEW AMERICAN VOICES', 'KATE FOR CONGRESS', 'CHRIS COONS FOR DELAWARE', 'ANTONE FOR CONGRESS', 'CONGRESSIONAL BLACK CAUCUS PAC', 'TORRES FOR CONGRESS', 'SARA GIDEON FOR MAINE', 'BIDEN FOR PRESIDENT', 'BULLOCK FOR PRESIDENT', 'MAGGIE TOULOUSE OLIVER FOR SENATE', 'WARREN DEMOCRATS, INC.', 'MONDAIRE FOR CONGRESS', 'AMMAR CAMPA-NAJJAR FOR CONGRESS', 'AMY FOR THE PEOPLE', 'AMY MCGRATH FOR SENATE, INC.', 'SUNRISE PAC', 'MONTANANS FOR BULLOCK', 'CHRIS BUBSER FOR CONGRESS', 'MCCREADY FOR CONGRESS', 'JUSTICE DEMOCRATS PAC', 'ELISE FOR CONGRESS', 'AMERICAN SOLIDARITY PARTY', 'JAIME HARRISON FOR US SENATE', 'DEB HAALAND FOR CONGRESS', 'CORY GARDNER FOR SENATE', 'PEOPLE FOR BEN', 'TRICIA ZUNKER FOR WISCONSIN', 'MCSALLY FOR SENATE INC', 'STOP REPUBLICANS', 'THE ACTION PAC', 'ARBALLO FOR CONGRESS', 'JON OSSOFF FOR SENATE', 'KAMALA HARRIS FOR THE PEOPLE', 'JOHN JAMES FOR SENATE, INC.', 'THOM TILLIS COMMITTEE', 'PEOPLE FIRST FUTURE', 'DEMOCRATIC PARTY OF WISCONSIN', 'PAC TO THE FUTURE', 'GOROFF FOR CONGRESS', 'JUSTIN AMASH FOR CONGRESS', 'TED LIEU FOR CONGRESS', 'CRISTINA FOR TEXAS', 'WINRED', 'REBELLION PAC', 'TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE', 'FRIENDS OF ANDREW YANG', 'THE PEOPLE FOR RUSH DARWISH', 'DEMOCRATS WORK FOR AMERICA, INC', 'HOWIE HAWKINS FOR OUR FUTURE', 'THE COMMITTEE TO ELECT AYANNA PRESSLEY', 'HER TIME PAC', 'BIDEN ACTION FUND', 'DITCH FUND', 'ALYSE FOR ALASKA', 'FRIENDS OF INTELLIGENT DEMOCRACY', 'CORY BOOKER FOR SENATE', 'JUDY CHU FOR CONGRESS', "TOM O'HALLERAN FOR CONGRESS", 'HATTERSLEY FOR CONGRESS', 'PENNSYLVANIA DEMOCRATIC PARTY', 'PEOPLE FOR GOVERNMENT PAC', 'WELCH FOR CONGRESS', 'YUKONG ZHAO FOR CONGRESS', 'LOPEZ FOR THE PEOPLE', 'RASHIDA TLAIB FOR CONGRESS', 'CORA FOR MONTANA', 'PACIFIC PALISADES DEMOCRATIC CLUB CAMPAIGN ACCOUNT', 'CHRISTY SMITH FOR CONGRESS', 'SHAHEEN FOR SENATE', 'CORY 2020', 'TOM WONG FOR CONGRESS', 'BENNET FOR AMERICA', 'CANDACE FOR 24', 'FAIR FIGHT', 'SEDINAM2020', 'PEOPLE POWERED ACTION', 'HICKENLOOPER FOR COLORADO', 'LEAHY FOR U.S. SENATOR COMMITTEE', 'DEMOCRATIC ACTION', 'COONS GROSS VICTORY FUND', 'CAPA21- FEDERAL', 'DR. CAMERON WEBB FOR CONGRESS', 'ELECT DEMOCRATIC WOMEN', 'FINELLO FOR CONGRESS', 'CAL FOR NC', 'TULSI ALOHA', 'LET AMERICA VOTE PAC', 'EVERYDAY PEOPLE', 'AMERICAN COLLEGE OF SURGEONS PROFESSIONAL ASSOCIATION PAC', 'VOTER PROTECTION PROJECT', 'FAIR GAME PAC', 'DEPASQUALE FOR PA 10', 'MOVEMENT VOTER PAC', 'DR. RAUL RUIZ FOR CONGRESS', 'BOOKER FOR THE PEOPLE, LTD', 'BIDEN VICTORY FUND', 'ARIZONA DEMOCRATIC PARTY', 'THE US CAMPAIGN FUND', 'DEMOCRATIC PARTY OF VIRGINIA', 'CAL CUNNINGHAM VICTORY FUND', 'MIJENTE PAC', 'PATRICIA TIMMONS-GOODSON FOR CONGRESS', 'GEORGIA FEDERAL ELECTIONS COMMITTEE', 'THE SQUAD VICTORY FUND', 'OHIO DEMOCRATIC PARTY', 'WYDEN FOR SENATE', 'MICHIGAN DEMOCRATIC STATE CENTRAL COMMITTEE', 'DAVID RICHTER FOR CONGRESS INC.', 'MINNESOTA DEMOCRATIC-FARMER-LABOR PARTY', 'ENGEL FOR CONGRESS', 'GEORGETTE GOMEZ FOR CONGRESS', 'JOYCE ELLIOTT FOR CONGRESS', 'TIFFANY SHEDD FOR CONGRESS COMMITTEE', 'VALADAO FOR CONGRESS', 'GREG RATHS FOR CONGRESS 2020', 'BYRON DONALDS FOR CONGRESS', 'HOLD THE HOUSE VICTORY FUND', 'TED HOWZE FOR CONGRESS 2020', 'FORWARD MAJORITY ACTION', 'BARBARA LEE FOR CONGRESS', 'GIDEON GREENFIELD 2020 VICTORY', 'RITA HART FOR IOWA', 'HANDEL FOR CONGRESS, INC.', 'COLLINS FOR SENATE, INC.', 'ASHLEY HINSON FOR CONGRESS', 'YOUNG FOR IOWA, INC.', 'BLUE SENATE CANDIDATE FUND', 'JACKIE GORDON FOR CONGRESS', 'VAN DREW FOR CONGRESS', 'BOWMAN FOR CONGRESS', 'SCHOLTEN FOR CONGRESS', 'SRI FOR CONGRESS', 'TONY GONZALES FOR CONGRESS', 'FLIP THE SENATE PAC', 'THERESA GREENFIELD FOR IOWA', 'COMMITTEE TO ELECT JARED GOLDEN', 'DALE CRAFTS FOR CONGRESS', 'NEVADANS FOR STEVEN HORSFORD', 'LAURA LOOMER FOR CONGRESS INC', 'MARIE NEWMAN FOR CONGRESS', 'BETSY DIRKSEN LONDRIGAN FOR CONGRESS', 'COLORADO DEMOCRATIC PARTY', 'BRIAN FITZPATRICK FOR CONGRESS', 'ANGIE CRAIG FOR CONGRESS', 'TEAM SCALISE', 'TERESA FOR ALL', 'TEXAS DEMOCRATIC PARTY', 'SUSIE LEE FOR CONGRESS']

In [15]:
susie = data[data.committee_name == 'SUSIE LEE FOR CONGRESS']

In [16]:
susie.contribution_receipt_amount.sum()

266.67

In [17]:
actblue = data[data.committee_name == 'ACTBLUE']

In [18]:
actblue.contribution_receipt_amount.sum()

430911.97000000003

In [19]:
final_data = []

In [20]:
len(newlist)

346

In [21]:
for x in newlist
sum(contribution_receipt_amount)

SyntaxError: invalid syntax (<ipython-input-21-6eef5d029568>, line 1)

In [22]:
final_data = []
for x in newlist: 
    final_data.append(data[data.committee_name == x].contribution_receipt_amount.sum())
print(final_data)

[8096.67, 430911.97000000003, 250.0, 796.49, 6200.18, 7000.0, 11875.0, 15360.220000000001, 3500.0, 3966.67, 4000.0, 41059.5, 73143.0, 1250.0, 1005.0, 1100.0, 6715.0, 350.0, 1075.0, 1967.0, 7270.0, 100.0, 655.25, 13122.029999999999, 800.0, 2015.9000000000003, 7147.5, 1156.2, 5293.0, 19665.0, -50.0, 800.0, 1016.0, 4100.0, 1375.0, 2000.0, 550.0, 4350.0, 230.0, 1901.0, 3500.0, 275.0, 2847.67, 300.0, 4182.08, 4344.5, 250.0, 130.37, 2084.18, 4250.0, 250.0, 3750.0, 2928.5, 250.0, 561.0, 4400.0, 2500.0, 1151.0, 944.0, 500.0, 971.0, 4700.0, 2000.0, 9450.0, 260.0, 2500.0, 4007.5, 500.0, 2500.0, 1750.0, 250.0, 50.0, 0.060000000000000005, 800.0, 8650.0, 2766.67, 4241.67, 250.0, 83.33, 250.0, 500.0, 4100.0, 350.0, 3450.0, 2250.0, 1366.67, 500.0, 2266.66, 500.0, 1250.0, 300.0, 3000.0, 766.6700000000001, 3000.0, 540.0, 9800.0, 5450.0, 1000.0, 3916.67, 550.0, 500.0, 6400.0, 1000.0, 3700.0, 2800.0, 486.0, 2050.0, 500.0, 13005.67, 2.5, 500.0, 500.0, 500.0, 500.0, 500.0, 5400.0, 1076.0, 7800.0, 3566.67, 3450.0, 2700.0, 250.0, 4916.67, 3200.0, 2.21, 1250.0, 3466.67, 850.0, 500.0, 4950.0, 7100.0, 500.0, 1100.0, 1066.67, 200.0, 3800.0, 250.0, 5000.0, 375.0, 7050.0, 2700.0, 270.0, 10500.0, 1327.0, 10.0, 360.0, 36.0, 3018.64, 1525.0, 300.0, 250.0, 1000.0, 3705.0, 1500.0, 900.0, 60.0, 500.0, 850.0, 677.0, 500.0, 290.0, 650.0, 400.0, 250.0, 500.0, 2500.0, 250.0, 250.0, 4060.0, 500.0, 1117.85, 500.0, 21148.0, 400.0, 4615.0, 750.0, 5000.0, 6250.0, 500.0, 24951.89, 866.6700000000001, 535.0, 21189.41, 13276.5, 500.0, 111998.5, 5000.0, 5600.0, 2050.0, 13439.5, 500.0, 250.0, 300.0, 1250.0, 250.0, 750.0, 3833.54, 5675.0, 250.0, 1250.0, 500.0, 5100.0, 310.5, 12.5, 6575.5, 186788.08000000002, 2350.0, 250.0, 3800.0, 250.0, 1663.0, 250.0, 2991.0, 54.0, 8600.0, 1750.0, 150.0, 75.0, 250.0, 2105.27, 3363.5, 250.0, 250.0, 5600.0, 1000.0, 550.0, 2242.5, 462.0, 252.5, 6100.0, 14034.0, 250.0, 750.0, 6559.35, 2866.64, 603.5, 2525.0, 100.0, 850.0, 1850.0, 31611.0, 100.0, 205.0, 385.0, 500.0, 200.0, 1289.92, 191.38, 1000.0, 1000.0, 850.0, 250.0, 500.0, 1000.0, 6600.0, 3.56, 1000.0, 1838.64, 1000.0, 11.530000000000001, 500.0, 133.84, 2249.4900000000002, 1000.0, 870.0, 2433.37, 75.0, 1178.0, 500.0, 4879.0, 1285.72, 1380.0, 250.0, 1015.0, 2800.0, 50.0, 430.0, 250.0, 700.0, 1000.0, 190.0, 1000.0, 7100.0, 250.0, 730.0, 100.0, 500.0, 125.0, 250.0, 766.6700000000001, 5750.0, 500.0, 302.14, 83850.0, 1770.35, 250.0, 1700.0, 1200.0, 250.0, 209.82, 1772.02, 937.0, 1700.0, 250.0, 1838.69, 100.0, 1700.0, 1000.0, 200.0, 500.0, 100.0, 200.0, 300.0, 90.0, 20000.0, 300.0, 259.6, 250.0, 250.0, 1266.67, 100.0, 200.0, 300.0, 100.0, 100.0, 266.67, 50.0, 127.0, 1000.0, 266.67, 300.0, 1000.0, 15943.83, 266.67, 300.0, 266.67, 450.0, 154.0, 766.6700000000001, 1700.0, 100.0, 766.6700000000001, 250.0, 250.0, 38.0, 266.67]

In [23]:
df  = pd.DataFrame()

In [24]:
df['committee_name'] = newlist

In [25]:
df['contribution_receipt_amount']  = final_data
print(df.head())

              committee_name  contribution_receipt_amount
0  HARLEY ROUDA FOR CONGRESS                      8096.67
1                    ACTBLUE                    430911.97
2     FRIENDS OF DANA BALTER                       250.00
3            IT STARTS TODAY                       796.49
4        END CITIZENS UNITED                      6200.18

In [29]:
df.sort_values('contribution_receipt_amount', ascending = False).head()

,committee_name,contribution_receipt_amount
1,ACTBLUE,430911.97
205,BIDEN FOR PRESIDENT,186788.08
185,DNC SERVICES CORP / DEMOCRATIC NATIONAL COMMITTEE,111998.50
293,BIDEN VICTORY FUND,83850.00
12,DCCC,73143.00